module "db" {
  source                 = "https://github.com/sandeep2k23/Terraform/blob/ECR/rds.tf"
  version                = "1.0.1"
  identifier_count       = 001
  region                 = "eu-central-1"
  application_code       = "sci"
  db_name                = "${lower(var.application)}${lower(var.environment)}"
  environment            = lower(var.environment)
  engine                 = "postgres"
  engine_version         = "15.2"
  instance_class         = "db.t3.small"
  allocated_storage      = 1000
  max_allocated_storage  = 1500
  vpc_security_group_ids = var.database_security_group_ids
  db_subnet_group_name   = var.database_subnet_group
  parameter_group_name   = "default.postgres15"
  multi_az               = false
  skip_final_snapshot    = false
  deletion_protection    = "true"
  tags                   = local.tags
}